//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horse_Isle_Hack_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Horse_Isle_Hack_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0: No Object
        ///60: PLAYERFOOD -- Acorn ($1)
        ///6: PLAYERFOOD -- Apple ($10)
        ///70: PLAYERFOOD -- Banana ($8)
        ///53: PLAYERFOOD -- Blackberry ($2)
        ///54: PLAYERFOOD -- Blueberry ($1)
        ///714: PLAYERFOOD -- Bunch of Grapes ($15)
        ///5: PLAYERFOOD -- Cake ($30)
        ///341: PLAYERFOOD -- Candy Cane ($5)
        ///186: PLAYERFOOD -- Carrot ($5)
        ///61: PLAYERFOOD -- Coconut ($20)
        ///44: PLAYERFOOD -- Coffee ($10)
        ///141: PLAYERFOOD -- Cookie ($7)
        ///689: PLAYERFOOD -- Cotton Candy ($5)
        ///55: PLAYERFOOD -- Cranberry ($1)
        ///445: PLAYERFOOD -- Easter Egg ($500)
        ///331: PLA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string item_ids {
            get {
                return ResourceManager.GetString("item_ids", resourceCulture);
            }
        }
    }
}
